# db config
spring:
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 12MB

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

# mybatis config
mybatis:
  type-aliases-package: com.teamd.tt
  mapper-locations: mapper/*.xml

# swagger
springdoc:
  swagger-ui:
    path: /swagger.html